### ISSUE TITLE
Improve installation guide

### ISSUE THREAD

**Issue by iimog** [molbiodiv/biojs-io-biom#30]
As a referee to our f1000 article notes:

> In my own installation of the software, I keep getting error messages when I attempt to create a biom object, see here: http://tinyurl.com/f1000-review. If the reviewers could please clarify the installation guide on the github repo.

Paulson J. Referee Report For: biojs-io-biom, a BioJS component for handling data in Biological Observation Matrix (BIOM) format [version 1; referees: 3 approved with reservations]. F1000Research 2016, 5:2348 (doi: 10.5256/f1000research.10362.r16545)

**Comment by iimog** [comment]
@nterhoeven please try to follow installation steps on your machine to find glitches

**Comment by nterhoeven** [comment]
I tried to reproduce the error shown above:

I installed the module via `npm`
```
>var Biom = require('biojs-io-biom')
> biom=new Biom()
TypeError: Biom is not a constructor
    at repl:1:6
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
> data = biom.data()
ReferenceError: biom is not defined
    at repl:1:8
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```
I got two errors -> the second one looks similar to the original one.

If I use `var Biom = require('biojs-io-biom').Biom` instead, everything works fine.
